### ISSUE TITLE
can't find variable: google

### ISSUE THREAD

**Issue by andrewarrow** [nfrankel/kotlin-frontend#2]
I get `can't find variable: google` in the browser on this line:

  KotlinGoogleMap.prototype = Object.create(google.maps.Map.prototype);

but my kotlin seems to compile it fun. Just a run-time error in the browser.

**Comment by nfrankel** [comment]
You perhaps need to replace the Google Maps API key with yours?
Hint: use Chrome Dev Tools to help you debug the cause.

**Comment by andrewarrow** [comment]
oh, hehe, my fault, forgot to include 

```
    <script src="https://maps.googleapis.com/maps/api/js?key=A123"></script>
```
on the page
